### ISSUE TITLE
大佬适配一下微信 8.0.50版本，这个版本更新10来天了

### ISSUE THREAD

**Issue by Timibabu** [Xposed-Modules-Repo/com.fkzhang.wechatxposed#110]
![QQ20240713-123859](https://github.com/user-attachments/assets/6be55563-5d04-4821-8c02-be1bdf5ee9e4)

**Comment by washingxian** [comment]
这个版本是不是进去设置都会闪退

**Comment by uihyyf** [comment]
智齿，求大佬适配

**Comment by Timibabu** [comment]
听说大佬进去了，后面的适配不了了，后面打赏也都用不了了

**Comment by uihyyf** [comment]
那就只能降级了
