### ISSUE TITLE
太极阴框架下微信时不时无响应，有人有这种情况吗

### ISSUE THREAD

**Issue by limingxi-angel** [Xposed-Modules-Repo/com.fkzhang.wechatxposed#53]
太极版本：14
微信版本：8.0.33
模块版本：2.4
太极阴框架下微信时不时无响应，需要等一会提示关闭应用重启微信后才会正常运行一段时间，过不了多久又卡死无响应，关闭模块后又一切恢复正常。请问有人遇到过这种情况吗？该怎么解决？

**Comment by Timibabu** [comment]
我的华为手机也是这样，用lspatch

**Comment by limingxi-angel** [comment]
> 我的华为手机也是这样，用lspatch

 换成lspatch现在好了，感恩
