### ISSUE TITLE
安全更新导致模块异常

### ISSUE THREAD

**Issue by askfname** [Xposed-Modules-Repo/com.fkzhang.wechatxposed#64]
Google Play的系统更新似乎会导致模块异常，表现是微信打开黑屏无响应。
![image](https://raw.githubusercontent.com/nasheep/images/main/Screenshot_20231008-190316.png)

删除/data/apex/active/目录下的安全更新文件可以恢复正常。
![image](https://raw.githubusercontent.com/nasheep/images/main/Screenshot_20231008-185518.png)

安全更新可能影响的是LSPosed框架，但是我这里的模块只有WeXposed受影响，不知道什么原因，先在这里提issue了。

WeXposed版本：2.42
微信版本：8.0.37（Play版）
LSPosed版本：1.9.1、1.8.6等多个版本
安卓版本：Android 13

**Comment by nanji233** [comment]
可以出Android14版本的吗

**Comment by fkzhang** [comment]
支持安卓14
